name: mooSelecta
author: D_mitar
category: Interface
description: Selecta
tags: [select, dropdown]
docs: http://fragged.org/mooSelecta/Docs/README.txt
demo: http://fragged.org/mooSelecta/Example/
current: v1.6.1